# Generated by Django 5.0.6 on 2026-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ynab_id', models.UUIDField(unique=True)),
                ('category_group_id', models.UUIDField()),
                ('category_group_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('hidden', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('budgeted', models.BigIntegerField()),
                ('activity', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('goal_type', models.CharField(blank=True, max_length=20, null=True)),
                ('goal_target', models.BigIntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
